<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo-PC" failures="1" tests="5" name="Default test" time="53.583" errors="0" timestamp="22 Apr 2018 14:17:14 GMT">
  <testcase classname="TestCase.SignupPageTest" name="ValidateFormFill" time="5.421"/>
  <testcase classname="TestCase.SignupPageTest" name="ValidateTitle" time="1.423">
    <skipped/>
  </testcase> <!-- ValidateTitle -->
  <testcase classname="TestCase.SignupPageTest" name="ValidateTitle" time="1.241">
    <skipped/>
  </testcase> <!-- ValidateTitle -->
  <testcase classname="TestCase.SignupPageTest" name="ValidateTitle" time="1.246">
    <skipped/>
  </testcase> <!-- ValidateTitle -->
  <testcase classname="TestCase.SignupPageTest" name="ValidateTitle" time="1.468">
    <failure type="java.lang.AssertionError" message="expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]">
      <![CDATA[java.lang.AssertionError: expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Pages.Signup.TitleCheck(Signup.java:81)
	at TestCase.SignupPageTest.ValidateTitle(SignupPageTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateTitle -->
</testsuite> <!-- Default test -->
