<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-04-22T14:31:02Z" name="CRM Application Test Automation Test Suite" finished-at="2018-04-22T14:32:37Z" duration-ms="94994">
    <groups>
    </groups>
    <test started-at="2018-04-22T14:31:02Z" name="CRM App Test Cases" finished-at="2018-04-22T14:32:37Z" duration-ms="94994">
      <class name="TestCase.SignupPageTest">
        <test-method is-config="true" signature="ReadFile()[pri:0, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:03Z" name="ReadFile" finished-at="2018-04-22T20:01:11Z" duration-ms="8612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadFile -->
        <test-method signature="ValidateFormFill()[pri:1, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:11Z" name="ValidateFormFill" finished-at="2018-04-22T20:01:18Z" duration-ms="6777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateFormFill -->
        <test-method is-config="true" signature="ReadFile()[pri:0, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:18Z" name="ReadFile" finished-at="2018-04-22T20:01:34Z" duration-ms="15841" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadFile -->
        <test-method signature="ValidateTitle()[pri:2, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:34Z" name="ValidateTitle" finished-at="2018-04-22T20:01:38Z" duration-ms="4035" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Pages.Signup.TitleCheck(Signup.java:81)
	at TestCase.SignupPageTest.ValidateTitle(SignupPageTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
        <test-method is-config="true" signature="ReadFile()[pri:0, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:38Z" name="ReadFile" finished-at="2018-04-22T20:01:52Z" duration-ms="13879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadFile -->
        <test-method signature="ValidateTitle()[pri:2, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:52Z" name="ValidateTitle" finished-at="2018-04-22T20:01:53Z" duration-ms="1702" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Pages.Signup.TitleCheck(Signup.java:81)
	at TestCase.SignupPageTest.ValidateTitle(SignupPageTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
        <test-method is-config="true" signature="ReadFile()[pri:0, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:01:53Z" name="ReadFile" finished-at="2018-04-22T20:02:08Z" duration-ms="14283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadFile -->
        <test-method signature="ValidateTitle()[pri:2, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:02:08Z" name="ValidateTitle" finished-at="2018-04-22T20:02:09Z" duration-ms="1513" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Pages.Signup.TitleCheck(Signup.java:81)
	at TestCase.SignupPageTest.ValidateTitle(SignupPageTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
        <test-method is-config="true" signature="ReadFile()[pri:0, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:02:09Z" name="ReadFile" finished-at="2018-04-22T20:02:35Z" duration-ms="25638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReadFile -->
        <test-method signature="ValidateTitle()[pri:2, instance:TestCase.SignupPageTest@5f683daf]" started-at="2018-04-22T20:02:35Z" name="ValidateTitle" finished-at="2018-04-22T20:02:37Z" duration-ms="2657" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CRMPRO - CRM Pro for customer relationship management, sales, and suppor] but found [CRMPRO - CRM Pro for customer relationship management, sales, and support]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Pages.Signup.TitleCheck(Signup.java:81)
	at TestCase.SignupPageTest.ValidateTitle(SignupPageTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
      </class> <!-- TestCase.SignupPageTest -->
    </test> <!-- CRM App Test Cases -->
  </suite> <!-- CRM Application Test Automation Test Suite -->
</testng-results>
